// Code generated by protoc-gen-gateway. DO NOT EDIT.

package user

import "github.com/MonsterYNH/protoc-gen-gateway/route"

func init() {

	if err := route.HTTPInfos.RegistInfo(route.Info{
		ServiceName:  "Login",
		Type:         "http",
		Method:       "post",
		Pattern:      "/login",
		RequestType:  ".user.LoginRequest",
		ResponseType: ".user.UserInfo",
	}); err != nil {
		panic("route: route regist failed")
	}

	if err := route.HTTPInfos.RegistInfo(route.Info{
		ServiceName:  "Logout",
		Type:         "http",
		Method:       "post",
		Pattern:      "/logout",
		RequestType:  ".user.LogoutEntry",
		ResponseType: ".user.LogoutEntry",
	}); err != nil {
		panic("route: route regist failed")
	}

	if err := route.HTTPInfos.RegistInfo(route.Info{
		ServiceName:  "GetUserInfo",
		Type:         "http",
		Method:       "get",
		Pattern:      "/user/info/{id}",
		RequestType:  ".user.GetUserInfoEntry",
		ResponseType: ".user.UserInfo",
	}); err != nil {
		panic("route: route regist failed")
	}

}
