// Code generated by protoc-gen-gateway. DO NOT EDIT.

package user

import "github.com/MonsterYNH/protoc-gen-gateway/route"

func init() {

	if err := route.HTTPInfos.RegistInfo(route.Info{
		ServiceName:  "User",
		Type:         "gql",
		Method:       "QUERY",
		Pattern:      "GetUserInfo",
		RequestType:  "user.GetUserInfoEntry",
		ResponseType: "user.UserInfo",
	}); err != nil {
		panic("route: route regist failed")
	}

}
