// Code generated by proroc-gen-graphql, DO NOT EDIT.
package user

import (
	"context"

	"github.com/graphql-go/graphql"
	"github.com/pkg/errors"
	"github.com/ysugimoto/grpc-graphql-gateway/runtime"
	"google.golang.org/grpc"
)

var (
	gql__enum_UserInfo_Sex      *graphql.Enum        // enum UserInfo_Sex in user/info.proto
	gql__type_UserInfo          *graphql.Object      // message UserInfo in user/info.proto
	gql__type_LogoutEntry       *graphql.Object      // message LogoutEntry in user/info.proto
	gql__type_LoginRequest      *graphql.Object      // message LoginRequest in user/info.proto
	gql__type_GetUserInfoEntry  *graphql.Object      // message GetUserInfoEntry in user/info.proto
	gql__input_UserInfo         *graphql.InputObject // message UserInfo in user/info.proto
	gql__input_LogoutEntry      *graphql.InputObject // message LogoutEntry in user/info.proto
	gql__input_LoginRequest     *graphql.InputObject // message LoginRequest in user/info.proto
	gql__input_GetUserInfoEntry *graphql.InputObject // message GetUserInfoEntry in user/info.proto
)

func Gql__enum_UserInfo_Sex() *graphql.Enum {
	if gql__enum_UserInfo_Sex == nil {
		gql__enum_UserInfo_Sex = graphql.NewEnum(graphql.EnumConfig{
			Name: "User_Enum_UserInfo_Sex",
			Values: graphql.EnumValueConfigMap{
				"WOMAN": &graphql.EnumValueConfig{
					Value: UserInfo_Sex(0),
				},
				"MAN": &graphql.EnumValueConfig{
					Value: UserInfo_Sex(1),
				},
				"UNKNOWN": &graphql.EnumValueConfig{
					Value: UserInfo_Sex(2),
				},
			},
		})
	}
	return gql__enum_UserInfo_Sex
}

func Gql__type_UserInfo() *graphql.Object {
	if gql__type_UserInfo == nil {
		gql__type_UserInfo = graphql.NewObject(graphql.ObjectConfig{
			Name: "User_Type_UserInfo",
			Fields: graphql.Fields{
				"id": &graphql.Field{
					Type: graphql.String,
				},
				"account": &graphql.Field{
					Type: graphql.String,
				},
				"password": &graphql.Field{
					Type: graphql.String,
				},
				"name": &graphql.Field{
					Type: graphql.String,
				},
				"phone_number": &graphql.Field{
					Type: graphql.String,
				},
				"address": &graphql.Field{
					Type: graphql.String,
				},
				"signure": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_UserInfo
}

func Gql__type_LogoutEntry() *graphql.Object {
	if gql__type_LogoutEntry == nil {
		gql__type_LogoutEntry = graphql.NewObject(graphql.ObjectConfig{
			Name: "User_Type_LogoutEntry",
			Fields: graphql.Fields{
				"account": &graphql.Field{
					Type: graphql.String,
				},
				"status": &graphql.Field{
					Type: graphql.Boolean,
				},
			},
		})
	}
	return gql__type_LogoutEntry
}

func Gql__type_LoginRequest() *graphql.Object {
	if gql__type_LoginRequest == nil {
		gql__type_LoginRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "User_Type_LoginRequest",
			Fields: graphql.Fields{
				"account": &graphql.Field{
					Type: graphql.String,
				},
				"password": &graphql.Field{
					Type: graphql.String,
				},
				"phone_number": &graphql.Field{
					Type: graphql.String,
				},
				"check_number": &graphql.Field{
					Type: graphql.NewNonNull(graphql.String),
				},
			},
		})
	}
	return gql__type_LoginRequest
}

func Gql__type_GetUserInfoEntry() *graphql.Object {
	if gql__type_GetUserInfoEntry == nil {
		gql__type_GetUserInfoEntry = graphql.NewObject(graphql.ObjectConfig{
			Name: "User_Type_GetUserInfoEntry",
			Fields: graphql.Fields{
				"id": &graphql.Field{
					Type: graphql.String,
				},
				"account": &graphql.Field{
					Type: graphql.String,
				},
				"phone_number": &graphql.Field{
					Type: graphql.String,
				},
				"token": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_GetUserInfoEntry
}

func Gql__input_UserInfo() *graphql.InputObject {
	if gql__input_UserInfo == nil {
		gql__input_UserInfo = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "User_Input_UserInfo",
			Fields: graphql.InputObjectConfigFieldMap{
				"id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"account": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"password": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"name": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"phone_number": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"address": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"signure": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_UserInfo
}

func Gql__input_LogoutEntry() *graphql.InputObject {
	if gql__input_LogoutEntry == nil {
		gql__input_LogoutEntry = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "User_Input_LogoutEntry",
			Fields: graphql.InputObjectConfigFieldMap{
				"account": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"status": &graphql.InputObjectFieldConfig{
					Type: graphql.Boolean,
				},
			},
		})
	}
	return gql__input_LogoutEntry
}

func Gql__input_LoginRequest() *graphql.InputObject {
	if gql__input_LoginRequest == nil {
		gql__input_LoginRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "User_Input_LoginRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"account": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"password": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"phone_number": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"check_number": &graphql.InputObjectFieldConfig{
					Type: graphql.NewNonNull(graphql.String),
				},
			},
		})
	}
	return gql__input_LoginRequest
}

func Gql__input_GetUserInfoEntry() *graphql.InputObject {
	if gql__input_GetUserInfoEntry == nil {
		gql__input_GetUserInfoEntry = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "User_Input_GetUserInfoEntry",
			Fields: graphql.InputObjectConfigFieldMap{
				"id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"account": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"phone_number": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"token": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_GetUserInfoEntry
}

// graphql__resolver_User is a struct for making query, mutation and resolve fields.
// This struct must be implemented runtime.SchemaBuilder interface.
type graphql__resolver_User struct {

	// Automatic connection host
	host string

	// grpc dial options
	dialOptions []grpc.DialOption

	// grpc client connection.
	// this connection may be provided by user
	conn *grpc.ClientConn
}

// new_graphql_resolver_User creates pointer of service struct
func new_graphql_resolver_User(conn *grpc.ClientConn) *graphql__resolver_User {
	return &graphql__resolver_User{
		conn:        conn,
		host:        "localhost:50051",
		dialOptions: []grpc.DialOption{},
	}
}

// CreateConnection() returns grpc connection which user specified or newly connected and closing function
func (x *graphql__resolver_User) CreateConnection(ctx context.Context) (*grpc.ClientConn, func(), error) {
	// If x.conn is not nil, user injected their own connection
	if x.conn != nil {
		return x.conn, func() {}, nil
	}

	// Otherwise, this handler opens connection with specified host
	conn, err := grpc.DialContext(ctx, x.host, x.dialOptions...)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

// GetQueries returns acceptable graphql.Fields for Query.
func (x *graphql__resolver_User) GetQueries(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{
		"GetUserInfo": &graphql.Field{
			Type: Gql__type_UserInfo(),
			Args: graphql.FieldConfigArgument{
				"id": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
				"account": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
				"phone_number": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
				"token": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req GetUserInfoEntry
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for GetUserInfo")
				}
				client := NewUserClient(conn)
				resp, err := client.GetUserInfo(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC GetUserInfo")
				}
				return resp, nil
			},
		},
	}
}

// GetMutations returns acceptable graphql.Fields for Mutation.
func (x *graphql__resolver_User) GetMutations(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{}
}

// Register package divided graphql handler "without" *grpc.ClientConn,
// therefore gRPC connection will be opened and closed automatically.
// Occasionally you may worry about open/close performance for each handling graphql request,
// then you can call RegisterUserGraphqlHandler with *grpc.ClientConn manually.
func RegisterUserGraphql(mux *runtime.ServeMux) error {
	return RegisterUserGraphqlHandler(mux, nil)
}

// Register package divided graphql handler "with" *grpc.ClientConn.
// this function accepts your defined grpc connection, so that we reuse that and never close connection inside.
// You need to close it maunally when application will terminate.
// Otherwise, you can specify automatic opening connection with ServiceOption directive:
//
// service User {
//    option (graphql.service) = {
//        host: "host:port"
//        insecure: true or false
//    };
//
//    ...with RPC definitions
// }
func RegisterUserGraphqlHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return mux.AddHandler(new_graphql_resolver_User(conn))
}
