// Code generated by proroc-gen-graphql, DO NOT EDIT.
package helloworld

import (
	"context"

	"github.com/graphql-go/graphql"
	"github.com/pkg/errors"
	"github.com/ysugimoto/grpc-graphql-gateway/runtime"
	"google.golang.org/grpc"
)

var (
	gql__type_HelloWorldResponse  *graphql.Object      // message HelloWorldResponse in helloworld/helloworld.proto
	gql__type_HelloWorldRequest   *graphql.Object      // message HelloWorldRequest in helloworld/helloworld.proto
	gql__input_HelloWorldResponse *graphql.InputObject // message HelloWorldResponse in helloworld/helloworld.proto
	gql__input_HelloWorldRequest  *graphql.InputObject // message HelloWorldRequest in helloworld/helloworld.proto
)

func Gql__type_HelloWorldResponse() *graphql.Object {
	if gql__type_HelloWorldResponse == nil {
		gql__type_HelloWorldResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Helloworld_Type_HelloWorldResponse",
			Fields: graphql.Fields{
				"hello_java": &graphql.Field{
					Type: graphql.String,
				},
				"hello_go": &graphql.Field{
					Type: graphql.String,
				},
				"hello_node": &graphql.Field{
					Type: graphql.String,
				},
				"hello_react": &graphql.Field{
					Type: graphql.String,
				},
				"hello_docker": &graphql.Field{
					Type: graphql.String,
				},
				"hello_flutter": &graphql.Field{
					Type: graphql.String,
				},
				"hello_world": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_HelloWorldResponse
}

func Gql__type_HelloWorldRequest() *graphql.Object {
	if gql__type_HelloWorldRequest == nil {
		gql__type_HelloWorldRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Helloworld_Type_HelloWorldRequest",
			Fields: graphql.Fields{
				"name": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_HelloWorldRequest
}

func Gql__input_HelloWorldResponse() *graphql.InputObject {
	if gql__input_HelloWorldResponse == nil {
		gql__input_HelloWorldResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Helloworld_Input_HelloWorldResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"hello_java": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"hello_go": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"hello_node": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"hello_react": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"hello_docker": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"hello_flutter": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"hello_world": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_HelloWorldResponse
}

func Gql__input_HelloWorldRequest() *graphql.InputObject {
	if gql__input_HelloWorldRequest == nil {
		gql__input_HelloWorldRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Helloworld_Input_HelloWorldRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"name": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_HelloWorldRequest
}

// graphql__resolver_HelloWorldService is a struct for making query, mutation and resolve fields.
// This struct must be implemented runtime.SchemaBuilder interface.
type graphql__resolver_HelloWorldService struct {

	// Automatic connection host
	host string

	// grpc dial options
	dialOptions []grpc.DialOption

	// grpc client connection.
	// this connection may be provided by user
	conn *grpc.ClientConn
}

// new_graphql_resolver_HelloWorldService creates pointer of service struct
func new_graphql_resolver_HelloWorldService(conn *grpc.ClientConn) *graphql__resolver_HelloWorldService {
	return &graphql__resolver_HelloWorldService{
		conn:        conn,
		host:        "localhost:50051",
		dialOptions: []grpc.DialOption{},
	}
}

// CreateConnection() returns grpc connection which user specified or newly connected and closing function
func (x *graphql__resolver_HelloWorldService) CreateConnection(ctx context.Context) (*grpc.ClientConn, func(), error) {
	// If x.conn is not nil, user injected their own connection
	if x.conn != nil {
		return x.conn, func() {}, nil
	}

	// Otherwise, this handler opens connection with specified host
	conn, err := grpc.DialContext(ctx, x.host, x.dialOptions...)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

// GetQueries returns acceptable graphql.Fields for Query.
func (x *graphql__resolver_HelloWorldService) GetQueries(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{
		"HelloWorld": &graphql.Field{
			Type: Gql__type_HelloWorldResponse(),
			Args: graphql.FieldConfigArgument{
				"name": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req HelloWorldRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for HelloWorld")
				}
				client := NewHelloWorldServiceClient(conn)
				resp, err := client.Greating(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC Greating")
				}
				return resp, nil
			},
		},
	}
}

// GetMutations returns acceptable graphql.Fields for Mutation.
func (x *graphql__resolver_HelloWorldService) GetMutations(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{}
}

// Register package divided graphql handler "without" *grpc.ClientConn,
// therefore gRPC connection will be opened and closed automatically.
// Occasionally you may worry about open/close performance for each handling graphql request,
// then you can call RegisterHelloWorldServiceGraphqlHandler with *grpc.ClientConn manually.
func RegisterHelloWorldServiceGraphql(mux *runtime.ServeMux) error {
	return RegisterHelloWorldServiceGraphqlHandler(mux, nil)
}

// Register package divided graphql handler "with" *grpc.ClientConn.
// this function accepts your defined grpc connection, so that we reuse that and never close connection inside.
// You need to close it maunally when application will terminate.
// Otherwise, you can specify automatic opening connection with ServiceOption directive:
//
// service HelloWorldService {
//    option (graphql.service) = {
//        host: "host:port"
//        insecure: true or false
//    };
//
//    ...with RPC definitions
// }
func RegisterHelloWorldServiceGraphqlHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return mux.AddHandler(new_graphql_resolver_HelloWorldService(conn))
}
