// Code generated by protoc-gen-gateway. DO NOT EDIT.

package helloworld

import "github.com/MonsterYNH/protoc-gen-gateway/route"

func init() {

	if err := route.HTTPInfos.RegistInfo(route.Info{
		ServiceName:  "Greating",
		Type:         "http",
		Method:       "get",
		Pattern:      "/helloworld",
		RequestType:  ".helloworld.HelloWorldRequest",
		ResponseType: ".helloworld.HelloWorldResponse",
	}); err != nil {
		panic("route: route regist failed")
	}

}
